export type JourneyStory = {
  storyId: string;
  storyNum: number;
  emoji: string;
  title: string;
  questions: string[];
};

export const journeyStories: JourneyStory[] = [
  { storyId: 'story-1', storyNum: 1, emoji: '🌱', title: 'A Little More About You', questions: [
    'What quality do you value most in yourself?',
    'What part of your personality are you still discovering?',
    'What situations bring out your most natural self?',
    'What is something you do without even thinking about it?',
    'What is something that feels true to who you are?',
    'What kind of environment helps you feel most like yourself?',
    'What tends to bring out your confidence?',
    'What are you naturally curious about?',
    'What quality would you never want to lose?',
    'What do you notice first when meeting someone new?',
  ] },
  { storyId: 'story-2', storyNum: 2, emoji: '🧠', title: 'The Way You Think', questions: [
    'How do you usually make an important decision?',
    'How do you handle uncertainty?',
    'Do you naturally think things through or decide as you go?',
    'What makes you change your mind?',
    'How do you feel about trying new things?',
    'What is your first thought when something goes wrong?',
    'Do you look for your own answers or ask someone first?',
    'What kinds of questions catch your attention?',
    'How do you learn something new best?',
    'What tends to spark your curiosity?',
  ] },
  { storyId: 'story-3', storyNum: 3, emoji: '🤍', title: 'People & Trust', questions: [
    'What helps you feel comfortable around someone?',
    'What do you value most in a friendship?',
    'What makes you trust someone?',
    'What breaks your trust?',
    'How quickly do you open up to people?',
    'What kind of people are you drawn to?',
    'What qualities do you appreciate in others?',
    'How do you respond when you disagree with someone?',
    'What makes a conversation feel meaningful to you?',
    'What is essential for a healthy relationship?',
  ] },
  { storyId: 'story-4', storyNum: 4, emoji: '🌿', title: 'Your Natural Habits', questions: [
    'What do you enjoy doing when you have time alone?',
    'What could hold your interest for hours?',
    'What do you usually do when you feel bored?',
    'Do you prefer having a plan or staying flexible?',
    'How do you react when a plan changes suddenly?',
    'What makes you lose track of time?',
    'Are you more organized or more comfortable going with the flow?',
    'What activity do you do purely for enjoyment?',
    'What kind of environment helps you concentrate?',
    'What makes an ordinary day feel good?',
  ] },
  { storyId: 'story-5', storyNum: 5, emoji: '💬', title: 'The Way You Communicate', questions: [
    'What do you enjoy most about talking with someone?',
    'Do you usually listen first or share first?',
    'What kind of advice do you prefer receiving?',
    'How do you express that something is important to you?',
    'What kind of conversations do you enjoy most?',
    'Are you more direct or more gentle when you communicate?',
    'What helps you feel heard?',
    'How do you handle a misunderstanding?',
    'What helps you keep a conversation going?',
    'What kind of communication feels difficult for you?',
  ] },
  { storyId: 'story-6', storyNum: 6, emoji: '🌧️', title: 'When Things Get Difficult', questions: [
    'What is your first reaction when something goes wrong?',
    'What helps you get through hard days?',
    'Do you talk about difficult feelings or keep them inside?',
    'What helps you calm down when you feel overwhelmed?',
    'How do you usually handle disappointment?',
    'What kind of criticism is hardest for you to hear?',
    'What helps you regain confidence?',
    'How do you respond when you make a mistake?',
    'What kind of support do you need most?',
    'What helps you move forward after being hurt?',
  ] },
  { storyId: 'story-7', storyNum: 7, emoji: '✨', title: 'What Matters to You', questions: [
    'What kind of behavior do you respect?',
    'What quality do you admire in someone else?',
    'What is a belief you feel strongly about?',
    'Would you rather feel understood or accepted?',
    'What behavior is intolerable to you?',
    'What makes someone trustworthy?',
    'What does being a good person mean to you?',
    'What would you stand up for?',
    'Do you value progress or recognition more?',
    'What principle is non-negotiable for you?',
  ] },
  { storyId: 'story-8', storyNum: 8, emoji: '🎨', title: 'Curiosity, Interests & Your World', questions: [
    'What kinds of things trigger your curiosity?',
    'What topics do you like learning about on your own?',
    'What kind of content can hold your attention for a long time?',
    'Do you prefer discovering something new or returning to something familiar?',
    'What kind of technology interests you?',
    'What do you explore first when you get a new device?',
    'What kinds of things do you enjoy creating?',
    'What hobbies come naturally to you?',
    'What do you like learning just for yourself?',
    'What interest represents you best?',
  ] },
  { storyId: 'story-9', storyNum: 9, emoji: '🌸', title: 'The Deeper You', questions: [
    'What do people commonly misunderstand about you?',
    'What quality in you often goes unnoticed?',
    'What kind of appreciation feels genuine to you?',
    'What compliment has stayed with you?',
    'What is a side of you that not everyone sees?',
    'When do you feel most authentic?',
    'What mindset have you outgrown?',
    'What has your journey of understanding yourself been like?',
    'What trait in you do you understand best?',
    'Where should someone start if they want to understand you?',
  ] },
  { storyId: 'story-10', storyNum: 10, emoji: '🌅', title: "The Person You're Becoming", questions: [
    'What do you imagine when you think about your future self?',
    'What strength do you want to build?',
    'What would a meaningful life look like to you?',
    'What keeps you motivated during hardship?',
    'What moments have made you feel proud?',
    'What experience do you hope to have in the future?',
    'What quality in you do you hope never changes?',
    'What do you think your future self will thank you for?',
    'What would you like to leave in the hearts of people close to you?',
    'What three words summarize the person you are becoming?',
  ] },
];